version: 0.2

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>" ## <TASK_DEFINITION>という文字列を置き換えることなくそのまま使用してください。
        LoadBalancerInfo:
            ContainerName: "test-con" ##適切な名前に置き換えてください
            ContainerPort: "80" ##適切なポート番号に置き換えてください