version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_ACCOUNT_ID: 196092325216
    IMAGE_REPO_NAME: nginx-fargate
    IMAGE_TAG: latest2

phases:
  build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_URI:IMAGE_TAG
      - docker push $IMAGE_URI:IMAGE_TAG
      - echo "[{\"name\":\"nginx-fargate\",\"imageUri\":\"$IMAGE_URI\"}]" > appspec.json

artifacts:
  files:
    - appspec.json